### ISSUE TITLE
Error: "Cannot find module 'babylon/lib/tokenizer/types'"

### ISSUE THREAD

**Issue by gnestor** [eponymous-labs/babel-plugin-top-level-await#2]
I tried to run the test and I got the following error:

```
$ babel-node --presets es2015 transform.js
module.js:457
    throw err;
    ^

Error: Cannot find module 'babylon/lib/tokenizer/types'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (top-level-await.js:22:1)
    at Module._compile (module.js:556:32)
    at loader (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:148:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:158:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

Before, I installed the required dependencies: `npm install babel-core babel-preset-es2015 babel-preset-stage-1`

It looks like babylon doesn't expose `/src` via the npm package (which includes `/tokenizer` and `/parser`, only `index.js` which only exports `parse` and `tokTypes`: https://github.com/babel/babylon/blob/32d5c7195ea18c90d1148a9dafeb46c97bbfe661/src/index.js#L19-L23

**Comment by gnestor** [comment]
It looks like the latest version of babylon was installed for some reason. I did a `grant:babel-plugin-top-level-await grant$` and now I'm just getting a babel compile error:

```
SyntaxError: unknown: Unexpected token (4:17)
  2 | import fs from "fs-promise"
  3 | 
> 4 | var text = await fs.readFile('README.md', 'utf-8')
    |                  ^
  5 | 
  6 | console.log(text)
    at Parser.pp$5.raise (/Users/grant/Sites/opensource/babel-plugin-top-level-await/node_modules/babel-core/node_modules/babylon/lib/index.js:4215:13)
    at Parser.pp.unexpected (/Users/grant/Sites/opensource/babel-plugin-top-level-await/node_modules/babel-core/node_modules/babylon/lib/index.js:1599:8)
    at Parser.pp$3.parseAwait (/Users/grant/Sites/opensource/babel-plugin-top-level-await/node_modules/babel-core/node_modules/babylon/lib/index.js:4119:10)
    at Parser.pp$3.parseExprAtom (/Users/grant/Sites/opensource/babel-plugin-top-level-await/node_modules/babel-core/node_modules/babylon/lib/index.js:3462:23)
    at Parser.pp$3.parseExprSubscripts (/Users/grant/Sites/opensource/babel-plugin-top-level-await/node_modules/babel-core/node_modules/babylon/lib/index.js:3305:19)
    at Parser.pp$3.parseMaybeUnary (/Users/grant/Sites/opensource/babel-plugin-top-level-await/node_modules/babel-core/node_modules/babylon/lib/index.js:3285:19)
    at Parser.pp$3.parseExprOps (/Users/grant/Sites/opensource/babel-plugin-top-level-await/node_modules/babel-core/node_modules/babylon/lib/index.js:3215:19)
    at Parser.pp$3.parseMaybeConditional (/Users/grant/Sites/opensource/babel-plugin-top-level-await/node_modules/babel-core/node_modules/babylon/lib/index.js:3192:19)
    at Parser.pp$3.parseMaybeAssign (/Users/grant/Sites/opensource/babel-plugin-top-level-await/node_modules/babel-core/node_modules/babylon/lib/index.js:3155:19)
    at Parser.pp$1.parseVar (/Users/grant/Sites/opensource/babel-plugin-top-level-await/node_modules/babel-core/node_modules/babylon/lib/index.js:2177:24)
```

I'll close this and open a new issue...
